### ISSUE TITLE
asa.unittest did not copy custom functions

### ISSUE THREAD

**Issue by soniachan** [Fleid/asa.unittest#12]
Functions are not cloned to test execution and the generated .asaproj file

**Comment by soniachan** [comment]
Workaround is to reference the custom functions in the .asaproj file

`<Configure Include=".\..\..\..\..\..\$asaProjectName\Functions\myFunc.js.json">
<SubType>JSFunction</SubType>
</Configure>`

**Comment by Fleid** [comment]
Fixed in 1.0.9
