### ISSUE TITLE
Start-AutRun does not support project names that contain a dot

### ISSUE THREAD

**Issue by Tecnova21** [Fleid/asa.unittest#13]
In our project we have a naming convention for Visual Studio projects like X.X.X.ASA.ProjectName.
When Start a new AutRun the call gets rejected by the validation.

Is there a specific reason why dots are not included in the naming validation?

**Comment by Fleid** [comment]
The main reason is that I'm that not as clever as I think with Regex ;)
Fixing that in the next release

**Comment by Fleid** [comment]
Actually, the validation is to be done on project name / asaql name.
Since in my experience  **folder name** = **project name** = **.asaql name**, I made a shortcut and implemented it at the folder name level.
I need to re-think this.

**Comment by Fleid** [comment]
Fixed in 1.0.9
